[김주현] Add : postings앱  제품후기 등록 기능구현
wecode-bootcamp-korea/25-1st-SPAOGAME-backend pull request #8
Opened 2021-10-09 09:06 UTC by kjhabc2002

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품  후기 등록 기능구현 
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 연관 데이터를 입력하면 후기 등록

![스크린샷, 2021-10-09 17-32-27](https://user-images.githubusercontent.com/41711271/136651689-527fe598-a975-45e4-a049-3e58906ce714.png)

![스크린샷, 2021-10-09 17-57-56](https://user-images.githubusercontent.com/41711271/136651710-5634a1cb-48b8-4e37-ad7f-2d79ab1da701.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

-리스트된 이미지데이터를 하나씩 가져오게 하는 로직에 대해 고민하게 되었고, for문을 통해 로직을 구현할 수 있다는 것을 알게 되었습니다.
 
<br />

## :: 기타 질문 및 특이 사항

2021-10-10 14:11 UTC, jamessoun93 requested changes

2021-10-10 14:11 UTC, jamessoun93 commented on postings/views.py
> +            title       = data.get('title',None)
`title` 이 `NULL` 허용 필드가 아닌데 선택사항으로 받고 계시네요? 이렇게 하신 이유가 있을까요?

2021-10-10 14:11 UTC, jamessoun93 commented on postings/views.py
> +                    )
- 이 부분은 `transaction` 이 필요합니다.
- 데이터베이스에서 `transaction` 이 무엇인지 알아보시고 여기서 왜 `transaction` 이 필요한지 설명해주세요.
- 그리고 나서 `django` 에서 `transaction` 을 어떻게 적용할 수 있는지 알아보시고 적용해주세요.

2021-10-10 14:11 UTC, jamessoun93 commented on postings/views.py
> +
불필요한 공백은 지워주세요.

2021-10-11 02:48 UTC, kjhabc2002 commented on postings/views.py
> +            title       = data.get('title',None)
null허용필드인줄 알고, keyerror를 반환하기 위해서 get을 썼던 건데 아니었군요ㅎㅎ;;
title = data['title']로 코드수정하겠습니다.

2021-10-11 09:03 UTC, kjhabc2002 commented on postings/views.py
> +                    )
product와 image테이블의 데이터를 한번에 처리하려면 데이터베이스 업데이트 변경이 한번에 이루어져야 하는데, 어느 한테이블에 데이터 유실? 이 생기는 경우가 있어서 db transaction으로 업데이트를 단일화된 작업으로 처리해야 데이터베이스 성능이 올라간다고 배웠습니다.

2021-10-12 13:57 UTC, jamessoun93 commented on postings/views.py
> +                        )
주현님! 여기는 반복문으로 돌면서 `create()` 쿼리를 계속 날리는것보다 `bulk_create()` 로 한번에 처리하는게 더 효율적입니다. 찾아서 적용해보시고 어떤 차이가 있는지 댓글로 설명해주세요.

2021-10-12 13:58 UTC, jamessoun93 commented on postings/views.py
> +            with transaction.atomic():
transaction 적용 잘하셨습니다 👍

2021-10-13 01:46 UTC, kjhabc2002 commented on postings/views.py
> +                        )
bulk_create()은 대량의 데이터를 한번에 db에 넣을 때 사용하는 메소드로 
create()메소드를 사용하는 것보다 데이터를 db에 넣는데 적은 시간이 소요된다는 장점이 있다는 것을 이번에 공부하면서  알게되었습니다.
적용해보니 코드길이도 간소화되고, 처리속도는 별로 차이를 느끼진 못하였으나 db관리에 효율적이라고 생각합니다.

2021-10-13 04:02 UTC, kjhabc2002 commented
bulk_create method 적용하여 코드수정 완료하였습니다. 
확인 부탁드립니다.

2021-10-13 05:50 UTC, jamessoun93 approved these changes
LGTM 👍
수고하셨습니다!

2021-10-13 05:50 UTC, merged